version: "3.8"
name: homework-2-8
services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: homework-2-8
    networks:
        - clickhouse
    ulimits:
        nofile:
          soft: 262144
          hard: 262144 
    ports:
      - "8123:8123"
    volumes:
      - volume:/var/lib/clickhouse
      - ./initdb:/docker-entrypoint-initdb.d

volumes:
  volume:
networks:
  clickhouse: